<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
</head>

<body>

  <div class="jumbotron text-center" style="margin-bottom: 0px;">
    <a href="usuario_registrado.php"><h1>Wordnews</h1></a>
  </div>

  <div class="container" align="center" style="padding:100px">
    <form class="col-md-7" action="#" method="post">
      <div class="form-group" align="left">
        <label for="titulo">Titulo:</label>
        <input type="text" class="form-control" id="titulo" name="titulo">
      </div>
      <div class="form-group" align="left">
        <label for="subtitulo">Subtitulo:</label>
        <input type="text" class="form-control" id="subtitulo" name="subtitulo">
      </div>
      <div class="form-group" align="left">
        <label for="seccion">Sección:</label>
        <select class="form-control" id="seccion" name="seccion">
            <option>Sección...</option>
            <option>Deportes</option>
            <option>Política</option>
            <option>Cultura</option>
            <option>Internacional</option>
            <option>Economía</option>
        </select>
      </div>
      <div class="form-group" align="left">
        <label for="cuerpo">Cuerpo de la noticia:</label>
        <textarea class="form-control" rows="10" id="cuerpo" name="cuerpo"></textarea>
      </div>
      <div class="form-group" align="left">
        <label for="imagen">Imagen (Opcional):</label>
        <input type="text" class="form-control" id="imagen" name="imagen" placeholder="url de la imagen">
      </div>
      <div class="form-group" align="left">
        <label for="keywords">Palabras clave:</label>
        <input type="text" class="form-control" id="keywords" name="keywords" placeholder="separadas por un espacio">
      </div>
      <button type="submit" class="btn btn-primary btn-lg btn-block">Crear artículo</button>

    </form>

  </div>

</body>
  <footer class="page-footer" style="background-color: lightgrey">

      <div class="container" style="padding: 50px">
        <div class="row" align="center">
          <h3 class="col-md-6 font-weight-bold font-size-30">Sobre Nosotros</h3>
          <h3 class="col-md-6 font-weight-bold">FAQS</h3>
        </div>
      </div>

    </footer>
</html>
