<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
</head>

<body>

  <div class="jumbotron text-center" style="margin-bottom: 0px;">
    <h1>Nombre de la web</h1>
  </div>

  <div class="container" align="center" style="padding:100px;">
    <form class="col-md-5" action="#" method="post">
      <div class="form-group" align="left">
        <label for="nombre">Nombre de usuario:</label>
        <input type="text" class="form-control" id="nombre" name="nombre">
      </div>
      <div class="form-group" align="left">
        <label for="pass">Contraseña</label>
        <input type="password" class="form-control" id="pass" name="pass">
      </div>
      <button type="submit" class="btn btn-primary btn-lg btn-block">Iniciar Sesión</button>

    </div>
  </div>

</body>


<footer class="page-footer" style="background-color: lightgrey">
  <div class="container" style="padding: 50px">
    <div class="row" align="center">
      <h3 class="col-md-6 font-weight-bold font-size-30">Sobre Nosotros</h3>
      <h3 class="col-md-6 font-weight-bold">FAQS</h3>
    </div>
  </div>
</footer>
</html>
