<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
</head>

<body>

  <div class="jumbotron text-center" style="margin-bottom: 0px;">
    <h1>Nombre de la web</h1>
  </div>


<!--se utilizara PHP para obtener los datos de la noticia y mostrarlos en los campos del formulario-->
<div class="container" align="center" style="padding:100px">
<?php
    foreach($articulo as $dato){

    }
    foreach($seccion as $sec){
        @$seccion=$sec['nombre'];
    }

  ?>

    <form action="#" method="post" class="col-md-7">
      <div class="form-group" align="left">
        <label for="titulo">Titulo:</label>
        <input type="text" class="form-control" id="titulo" name="titulo" value="<?php echo $dato['titulo'];?>">
      </div>

      <div class="form-group" align="left">
        <label for="subtitulo">Subtitulo:</label>
        <input type="text" class="form-control" id="subtitulo" name="subtitulo" value="<?php echo $dato['subtitulo'];?>">
      </div>
      <div class="form-group" align="left">
        <label for="seccion">Seccion:</label>
        <input type="text" class="form-control" id="seccion" name="seccion" value="<?php echo $seccion; ?>">
      </div>
      <div class="form-group" align="left">
        <label for="cuerpo">Cuerpo de la noticia:</label>
        <textarea class="form-control" rows="10" id="cuerpo" name="cuerpo" ><?php echo $dato['cuerpo'];?></textarea>
      </div>
      <div class="form-group" align="left">
        <label for="imagen">Imagen (Opcional):</label>
        <input type="text" class="form-control" id="imagen" name="imagen" value="<?php echo $dato['imagen'];?>">
      </div>
      <div class="form-group" align="left">
        <label for="keywords">Palabras clave:</label>
        <input type="text" class="form-control" id="keywords" name="keywords" value="<?php
        /*foreach($keys as $key){
          echo $keywords=$key['keyword'];
        }*/
          for($i=0; $i<count($keys); $i++){
            echo @$keys[$i]['keyword'];
            if($i>1 && $i<count($keys)-1){
              echo " ";
            }

          }
        ?>">
      </div>

      <button type="submit" class="btn btn-primary btn-lg btn-block" name="btn">Modificar artículo</button>

    </div>
  </div>


  <footer class="page-footer" style="background-color: lightgrey">

      <div class="container" style="padding: 50px">
        <div class="row" align="center">
          <h3 class="col-md-6 font-weight-bold font-size-30">Sobre Nosotros</h3>
          <h3 class="col-md-6 font-weight-bold">FAQS</h3>
        </div>
      </div>

    </footer>
</html>
