<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" type="text/css" href="css/bootstrap.css">
</head>

<body>

  <div class="jumbotron text-center" style="margin-bottom: 0px;">
    <a href="usuario_registrado.php"><h1>Wordnews</h1></a>
  </div>

  <div class="container-fluid" style="background-color: lightgrey; padding-top:10px; padding-bottom:10px">

<!-- Según el tipo de usuario que se detecte con PHP se mostrará un menú o otro-->

<?php
foreach ($tipous as $dato){
    $tipousuario=$dato['tipousuario'];
}

if ($tipousuario=='periodista'){
    require_once("plantillas/nav_periodista.html");
}else if($tipousuario=='editor'){
    require_once("plantillas/nav_editor.html");
}else if($tipousuario=='admin'){
    require_once("plantillas/nav_admin.html");
}
?>


  </div>

  <div class="container" style="width:100%; margin: 0 auto;">

<!--Aqui iria el while en php para ir sacando las noticias de la bbdd-->

<?php
  for($i=0; $i<count($noticias); $i++){
    echo "<div class='row' style='width: 70%; margin: 0 auto; margin-top: 50px; margin-bottom: 50px; background-color:lightgrey; padding: 20px;'>";
    echo $noticias[$i]["titulo"]."<br/>";
    echo $noticias[$i]["subtitulo"]."<br/>";
    echo $noticias[$i]["cuerpo"]."<br/>";
    echo $noticias[$i]["fecha_creacion"]."<br/>";
    echo "</div>";
  }
?>

  </div>

</body>

<footer class="page-footer" style="background-color: lightgrey">

    <div class="container" style="padding: 50px">
      <div class="row" align="center">
        <h3 class="col-md-6 font-weight-bold font-size-30">Sobre Nosotros</h3>
        <h3 class="col-md-6 font-weight-bold">FAQS</h3>
      </div>
    </div>

  </footer>

</html>
